@echo off
rem Batch script to open Wikipedia episode lists for specified TV shows

start "" "https://en.wikipedia.org/wiki/List_of_3_Body_Problem_episodes"
start "" "https://en.wikipedia.org/wiki/List_of_Ahsoka_episodes"
start "" "https://en.wikipedia.org/wiki/List_of_Blue_Eye_Samurai_episodes"
start "" "https://en.wikipedia.org/wiki/List_of_Colin_From_Accounts_episodes"
start "" "https://en.wikipedia.org/wiki/List_of_Dune:_Prophecy_episodes"
start "" "https://en.wikipedia.org/wiki/List_of_Fallout_episodes"
start "" "https://en.wikipedia.org/wiki/List_of_Foundation_episodes"
start "" "https://en.wikipedia.org/wiki/List_of_Frisco_King_episodes"
start "" "https://en.wikipedia.org/wiki/List_of_Harley_Quinn_episodes"
start "" "https://en.wikipedia.org/wiki/List_of_High_Potential_episodes"
start "" "https://en.wikipedia.org/wiki/List_of_King_of_the_Hill_episodes"
start "" "https://en.wikipedia.org/wiki/List_of_Neagley_episodes"
start "" "https://en.wikipedia.org/wiki/List_of_Percy_Jackson_and_the_Olympians_episodes"
start "" "https://en.wikipedia.org/wiki/List_of_Reacher_episodes"
start "" "https://en.wikipedia.org/wiki/List_of_Return_to_Paradise_episodes"
start "" "https://en.wikipedia.org/wiki/List_of_Saint-Pierre_episodes"
start "" "https://en.wikipedia.org/wiki/List_of_Secret_Level_episodes"
start "" "https://en.wikipedia.org/wiki/List_of_Silo_episodes"
start "" "https://en.wikipedia.org/wiki/List_of_Special_Ops:_Lioness_episodes"
start "" "https://en.wikipedia.org/wiki/List_of_Star_Trek:_Strange_New_Worlds_episodes"
start "" "https://en.wikipedia.org/wiki/List_of_Ted_Lasso_episodes"
start "" "https://en.wikipedia.org/wiki/List_of_The_Amazing_Race_episodes"
start "" "https://en.wikipedia.org/wiki/List_of_The_Amazing_Race_(Australian_TV_series)_episodes"
start "" "https://en.wikipedia.org/wiki/List_of_The_Amazing_Race_Canada_episodes"
start "" "https://en.wikipedia.org/wiki/List_of_The_Lord_of_the_Rings:_The_Rings_of_Power_episodes"
start "" "https://en.wikipedia.org/wiki/List_of_The_Witcher_episodes"
start "" "https://en.wikipedia.org/wiki/List_of_Tulsa_King_episodes"
start "" "https://en.wikipedia.org/wiki/List_of_Wednesday_episodes"
start "" "https://en.wikipedia.org/wiki/List_of_Wild_Cards_episodes"